version: "3.8"

services:
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: talkboard
      POSTGRES_PASSWORD: testPasswd12JK9o
      POSTGRES_DB: talkboard
    volumes:
      - ./postgresql:/var/lib/postgresql/data/

  talkboard_app:
    build:
      context: ./talkboard-app/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://talkboard:NotStrongForTestAdminPswd@postgres:5432/talkboard
    volumes:
      - ./talkboard-app/:/app
      - /app/node_modules
    command: pnpm run start:dev
